[tool.black]
line-length = 120
target-version = ['py310', 'py311']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
'''

[tool.djlint]
profile='jinja'
indent=2
use_gitignore=true
